name: ebisu_mongo
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_mongo
description: >
  Support for generating code providing mongo data access patterns.

dependencies:

# custom <ebisu_mongo dependencies>

  logging: any

  path: any

  ebisu: "^0.6.6"

  ebisu_pod:
    git: git://github.com/patefacio/ebisu_pod

  ebisu_cpp: "^0.3.6"
  
# end <ebisu_mongo dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_mongo dev dependencies>

  test: any

# end <ebisu_mongo dev dependencies>

dependency_overrides:
# custom <ebisu_mongo dependency overrides>

  ebisu: 
    git: git://github.com/patefacio/ebisu

  ebisu_cpp: 
    git: git://github.com/patefacio/ebisu_cpp
    
# end <ebisu_mongo dependency overrides>

transformers:

# custom <ebisu_mongo transformers>
# end <ebisu_mongo transformers>

